apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dinesykmeldte
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.nav.no/arbeidsgiver/sykmeldte'
  accessPolicy:
    outbound:
      rules:
        - application: dinesykmeldte-backend
  prometheus:
    enabled: true
    path: /arbeidsgiver/sykmeldte/api/internal/prometheus
  idporten:
    enabled: true
    sidecar:
      enabled: true
      resources:
        requests:
          cpu: 100m
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  tokenx:
    enabled: true
  liveness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_alive
  readiness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_ready
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /arbeidsgiver/sykmeldte
    - name: RUNTIME_ENVIRONMENT
      value: prod
    - name: RUNTIME_VERSION
      value: {{version}}
    - name: DINE_SYKMELDTE_BACKEND_SCOPE
      value: prod-gcp:teamsykmelding:dinesykmeldte-backend
    - name: DINE_SYKMELDTE_BACKEND_URL
      value: https://dinesykmeldte-backend.intern.nav.no
    - name: ENABLE_SENTRY
      value: 'true'
    - name: ASSET_PREFIX
      value: "https://teamsykmelding-static-files.nav.no/dinesykmeldte"
