apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dinesykmeldte
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://www-gcp.dev.nav.no/syk/dinesykmeldte"
  idporten:
    enabled: true
    redirectPath: "/api/callback"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /syk/dinesykmeldte/api/is_alive
  readiness:
    path: /syk/dinesykmeldte/api/is_ready
  env:
  - name: SECRET_COOKIE_PASSWORD
    value: dfafewsfjeskafejsafeskalfjesaklfjeklasjfklsefjlsalkfekljasfjksejklfasekljfkljaskle
  - name: NEXT_PUBLIC_BASE_PATH
    value: /syk/dinesykmeldte
