apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dinesykmeldte
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://dinesykmeldte.labs.nais.io/'
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  tokenx:
    enabled: true
  liveness:
    path: /api/is_alive
  readiness:
    path: /api/is_ready
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: ~
    - name: RUNTIME_ENVIRONMENT
      value: labs
