apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dinesykmeldte
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www-gcp.dev.nav.no/syk/dinesykmeldte'
  idporten:
    enabled: true
    sidecar:
      enabled: true
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  tokenx:
    enabled: true
  liveness:
    path: /syk/dinesykmeldte/api/is_alive
  readiness:
    path: /syk/dinesykmeldte/api/is_ready
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /syk/dinesykmeldte
    - name: RUNTIME_ENVIRONMENT
      value: q1
    - name: DINE_SYKMELDTE_BACKEND_SCOPE
      value: dev-gcp:teamsykmelding:dinesykmeldte-backend
    - name: DINE_SYKMELDTE_BACKEND_URL
      value: https://dinesykmeldte-backend.dev.nav.no
