apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dinesykmeldte-demo
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://dinesykmeldte.ekstern.dev.nav.no/arbeidsgiver/sykmeldte'
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  tokenx:
    enabled: true
  liveness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_alive
  readiness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_ready
  env:
    - name: RUNTIME_ENVIRONMENT
      value: demo
    - name: RUNTIME_VERSION
      value: demo
    - name: AMPLITUDE_ENABLED
      value: 'false'
