name: Build & Deploy
on: push

jobs:
  next-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/next-app.yaml@main
    secrets: inherit
    with:
      app: dinesykmeldte
      base-path: /arbeidsgiver/sykmeldte
